url: "https://adham-e.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Adham" # the name of your site, e.g. ACME Corp.

# Social Info
youtube: https://www.youtube.com/channel/UCMXZwXFwd7tI7pO7vUo5iuQ
linkedin: https://www.linkedin.com/in/adham-elarabawy/
github: https://github.com/adham-elarabawy
